// Assessment Questions Library
// Ported from visa-commodities app — ALL questions included

export interface AssessmentQuestion {
  id: string;
  section: "registration" | "data_maturity" | "personal_ai" | "company_ai";
  dimension: string;
  text: string;
  type: "text" | "long-text" | "single-select" | "multi-select" | "likert" | "grid";
  options?: string[];
  gridItems?: string[];
  gridOptions?: string[];
  required: boolean;
  minLength?: number;
  maxLength?: number;
  maxSelections?: number;
  helpText?: string;
  category?: string;
}

// ─── REGISTRATION: Professional Identity ─────────────────────────────────────

export const REGISTRATION_QUESTIONS: AssessmentQuestion[] = [
  // --- Step 1: Professional Identity ---
  {
    id: "REG_NAME",
    section: "registration",
    dimension: "identity",
    text: "What is your full name?",
    type: "text",
    required: true,
    minLength: 2,
    maxLength: 200,
  },
  {
    id: "REG_EMAIL",
    section: "registration",
    dimension: "identity",
    text: "What is your work email address?",
    type: "text",
    required: true,
    minLength: 5,
    maxLength: 200,
    helpText: "We use this to link your assessment results to your profile.",
  },
  {
    id: "REG_COMPANY",
    section: "registration",
    dimension: "identity",
    text: "What company or organisation do you work for?",
    type: "text",
    required: true,
    minLength: 2,
    maxLength: 200,
  },
  {
    id: "REG_WEBSITE",
    section: "registration",
    dimension: "identity",
    text: "What is your company website? (optional)",
    type: "text",
    required: false,
    maxLength: 500,
  },
  {
    id: "REG_INDUSTRY",
    section: "registration",
    dimension: "identity",
    text: "Which industry does your organisation primarily operate in?",
    type: "single-select",
    options: [
      "Oil, Gas & Energy",
      "Wholesale & Trading",
      "Retail & Consumer Goods",
      "Manufacturing & Industrial",
      "Healthcare & Life Sciences",
      "Financial Services & Insurance",
      "Real Estate & Construction",
      "Logistics & Supply Chain",
      "Professional Services & Consulting",
      "Technology & Telecommunications",
      "Education & Research",
      "Hospitality & Tourism",
      "Government & Public Sector",
      "Other",
    ],
    required: true,
  },
  {
    id: "REG_EMPLOYEES",
    section: "registration",
    dimension: "identity",
    text: "How many employees does your organisation have?",
    type: "single-select",
    options: [
      "1\u201310 (Micro)",
      "11\u201350 (Small)",
      "51\u2013200 (Medium)",
      "201\u20131,000 (Large)",
      "1,001\u201310,000 (Enterprise)",
      "10,000+ (Global Enterprise)",
    ],
    required: true,
  },
  {
    id: "REG_ROLE",
    section: "registration",
    dimension: "identity",
    text: "What is your primary role?",
    type: "single-select",
    options: [
      "Founder / Owner",
      "C-Suite Executive (CEO, COO, CFO, CTO, etc.)",
      "Vice President / Senior Director",
      "Director / Head of Department",
      "Manager / Team Lead",
      "Senior Individual Contributor",
      "Analyst / Specialist",
      "Other",
    ],
    required: true,
  },
  {
    id: "REG_FUNCTION",
    section: "registration",
    dimension: "identity",
    text: "Which business function do you primarily work in?",
    type: "single-select",
    options: [
      "General Management / Executive Office",
      "Strategy & Corporate Development",
      "Finance & Accounting",
      "Operations & Supply Chain",
      "Sales & Business Development",
      "Marketing & Communications",
      "Human Resources & People",
      "Technology & IT",
      "Legal & Compliance",
      "Product & Innovation",
      "Other",
    ],
    required: true,
  },
  {
    id: "REG_TENURE",
    section: "registration",
    dimension: "identity",
    text: "How long have you been in your current role?",
    type: "single-select",
    options: [
      "Less than 6 months",
      "6 months \u2013 2 years",
      "2\u20135 years",
      "5\u201310 years",
      "More than 10 years",
    ],
    required: true,
  },

  // --- Step 2: Organisational Context ---
  {
    id: "REG_ORG_DESC",
    section: "registration",
    dimension: "org_context",
    text: "In your own words, briefly describe what your organisation does and its core business model.",
    type: "long-text",
    required: true,
    minLength: 10,
    maxLength: 500,
  },
  {
    id: "REG_CHALLENGES",
    section: "registration",
    dimension: "org_context",
    text: "What are the biggest operational challenges your organisation currently faces?",
    type: "long-text",
    required: true,
    minLength: 10,
    maxLength: 500,
  },
  {
    id: "REG_PRIORITIES",
    section: "registration",
    dimension: "org_context",
    text: "What are your organisation's top strategic priorities for the next 12\u201324 months?",
    type: "long-text",
    required: true,
    minLength: 10,
    maxLength: 500,
  },
  {
    id: "REG_TECH_APPETITE",
    section: "registration",
    dimension: "org_context",
    text: "How would you describe your organisation's appetite for adopting new technology?",
    type: "single-select",
    options: ["Pioneer", "Fast Follower", "Pragmatist", "Conservative", "Resistant"],
    required: true,
  },
  {
    id: "REG_BUDGET",
    section: "registration",
    dimension: "org_context",
    text: "Does your organisation have a dedicated budget for digital transformation or technology investment?",
    type: "single-select",
    options: [
      "Yes, with a formal annual budget allocation",
      "Yes, but it is informal / project-by-project",
      "No, technology costs come from departmental budgets",
      "I don't know",
    ],
    required: true,
  },

  // --- Step 3: AI Usage Context ---
  {
    id: "REG_AI_TOOLS",
    section: "registration",
    dimension: "ai_context",
    text: "Which AI tools or platforms does your organisation currently use? (Select all that apply)",
    type: "multi-select",
    options: [
      "Microsoft Copilot (M365 AI)",
      "ChatGPT (OpenAI)",
      "Claude (Anthropic)",
      "Google Gemini / Bard",
      "Salesforce Einstein / AI CRM tools",
      "HubSpot AI",
      "Zoho AI",
      "SAP AI / Oracle AI (ERP-embedded AI)",
      "Power BI / Tableau (BI & analytics tools)",
      "Zapier / Make (no-code automation)",
      "Custom-built AI or machine learning models",
      "RPA tools (UiPath, Automation Anywhere, Blue Prism)",
      "None of the above",
      "Other",
    ],
    required: true,
  },
  {
    id: "REG_AI_DURATION",
    section: "registration",
    dimension: "ai_context",
    text: "How long has your organisation been using AI tools?",
    type: "single-select",
    options: [
      "Less than 3 months",
      "3\u201312 months",
      "1\u20133 years",
      "More than 3 years",
      "Not applicable (none selected)",
    ],
    required: true,
  },
  {
    id: "REG_AI_OWNERS",
    section: "registration",
    dimension: "ai_context",
    text: "Who currently owns or drives AI initiatives in your organisation? (Select all that apply)",
    type: "multi-select",
    options: [
      "The CEO / Founder personally drives AI adoption",
      "A dedicated Chief Digital Officer (CDO) or Chief AI Officer (CAIO)",
      "The CTO or IT Director",
      "A cross-functional AI or Digital Transformation team",
      "Individual department heads driving adoption in their own teams",
      "External consultants or vendors",
      "No one \u2014 AI is not formally owned",
      "I don't know",
    ],
    required: true,
  },
  {
    id: "REG_AI_GOVERNANCE",
    section: "registration",
    dimension: "ai_context",
    text: "Does your organisation have an AI usage or governance policy?",
    type: "single-select",
    options: [
      "Yes \u2014 we have a documented AI usage policy that is communicated to staff",
      "Yes \u2014 we have informal guidelines but nothing formally documented",
      "No \u2014 but we are actively working on one",
      "No \u2014 and it is not currently a priority",
      "I don't know",
    ],
    required: true,
  },
  {
    id: "REG_AUTOMATION",
    section: "registration",
    dimension: "ai_context",
    text: "What percentage of your team's work do you estimate could be partially or fully automated with AI?",
    type: "single-select",
    options: [
      "Less than 10%",
      "10\u201325%",
      "26\u201350%",
      "51\u201375%",
      "More than 75%",
    ],
    required: true,
  },
  {
    id: "REG_AI_STAGE",
    section: "registration",
    dimension: "ai_context",
    text: "Which stage best describes your organisation's current AI adoption?",
    type: "single-select",
    options: [
      "Stage 0 \u2014 Unaware",
      "Stage 1 \u2014 Exploring",
      "Stage 2 \u2014 Piloting",
      "Stage 3 \u2014 Deploying",
      "Stage 4 \u2014 Scaling",
      "Stage 5 \u2014 Optimising",
    ],
    required: true,
  },
  {
    id: "REG_AI_EXAMPLE",
    section: "registration",
    dimension: "ai_context",
    text: "Describe one specific example of how AI is currently used in your organisation, or one opportunity you believe AI could address.",
    type: "long-text",
    required: true,
    minLength: 10,
    maxLength: 500,
  },

  // --- Step 4: Workflow Context ---
  {
    id: "REG_TIME_TASKS",
    section: "registration",
    dimension: "workflow",
    text: "What tasks consume the most time in your typical work week?",
    type: "long-text",
    required: true,
    minLength: 10,
    maxLength: 500,
  },
  {
    id: "REG_MANUAL_CATEGORIES",
    section: "registration",
    dimension: "workflow",
    text: "Which categories of work involve the most manual effort? (Select all that apply)",
    type: "multi-select",
    options: [
      "Data entry or data migration between systems",
      "Generating reports or dashboards",
      "Scheduling and calendar management",
      "Drafting documents, emails, or presentations",
      "Researching market intelligence or competitor data",
      "Reviewing and approving workflows",
      "Customer or supplier communication management",
      "Financial reconciliation or analysis",
      "Staff performance management",
      "Inventory or supply chain monitoring",
      "None of the above",
      "Other",
    ],
    required: true,
  },
  {
    id: "REG_BOTTLENECK",
    section: "registration",
    dimension: "workflow",
    text: "What is the single biggest workflow bottleneck in your team or department?",
    type: "long-text",
    required: true,
    minLength: 10,
    maxLength: 500,
  },
  {
    id: "REG_IDEAL_AI",
    section: "registration",
    dimension: "workflow",
    text: "If you could have an AI assistant that did one thing perfectly for you, what would it do?",
    type: "long-text",
    required: true,
    minLength: 10,
    maxLength: 500,
  },
];

// ─── DATA MATURITY ───────────────────────────────────────────────────────────

export const DATA_MATURITY_QUESTIONS: AssessmentQuestion[] = [
  // DIM_DA: Data Availability & Accessibility
  {
    id: "DA1",
    section: "data_maturity",
    dimension: "DIM_DA",
    text: "Where does your organisation's business-critical data primarily reside? (Select all that apply)",
    type: "multi-select",
    options: [
      "Cloud-based platforms (e.g., Google Cloud, AWS, Azure)",
      "On-premise servers or local data centres",
      "ERP or CRM systems (e.g., SAP, Salesforce, QuickBooks, Dynamics)",
      "Spreadsheets (Excel, Google Sheets)",
      "Paper records or physical filing systems",
      "Individual employees' devices or email inboxes",
      "A dedicated data warehouse or data lake",
      "I don't know",
    ],
    required: true,
  },
  {
    id: "DA2",
    section: "data_maturity",
    dimension: "DIM_DA",
    text: "How easy is it for you to access the data you need to make day-to-day business decisions?",
    type: "likert",
    options: [
      "1 \u2014 Extremely difficult. Data is fragmented, siloed, or requires manual effort to retrieve.",
      "2 \u2014 Difficult. Data is available but requires significant time or technical support to access.",
      "3 \u2014 Moderate. Data is accessible but not always in the format or level of detail needed.",
      "4 \u2014 Easy. Most data is readily accessible with minimal friction.",
      "5 \u2014 Very easy. Data is available on demand, in real time, in the format I need.",
    ],
    required: true,
  },
  {
    id: "DA3",
    section: "data_maturity",
    dimension: "DIM_DA",
    text: "For each of the following data types, does your organisation maintain a centralised, up-to-date system of record?",
    type: "grid",
    gridItems: [
      "Customer / Client data",
      "Supplier / Vendor data",
      "Financial and accounting data",
      "Inventory or product data",
      "Employee / HR data",
      "Sales and transaction data",
      "Operational / production data",
    ],
    gridOptions: ["Yes", "Partial", "No", "Don't Know"],
    required: true,
  },
  {
    id: "DA4",
    section: "data_maturity",
    dimension: "DIM_DA",
    text: "How frequently is your organisation's most critical business data updated?",
    type: "single-select",
    options: [
      "Real-time (continuous stream)",
      "Near real-time (every few minutes to hourly)",
      "Daily batch updates",
      "Weekly updates",
      "Monthly or less frequently",
      "Manual updates with no fixed schedule",
    ],
    required: true,
  },
  {
    id: "DA5",
    section: "data_maturity",
    dimension: "DIM_DA",
    text: "In the past 12 months, have you been unable to make a business decision because the data you needed was unavailable, delayed, or incomplete?",
    type: "single-select",
    options: [
      "Yes, frequently (several times per month)",
      "Yes, occasionally (a few times per quarter)",
      "Rarely (once or twice in the past year)",
      "No, this has not been an issue",
      "I don't know",
    ],
    required: true,
  },

  // DIM_DQ: Data Quality & Integrity
  {
    id: "DQ1",
    section: "data_maturity",
    dimension: "DIM_DQ",
    text: "How would you rate the overall quality of data in your organisation?",
    type: "likert",
    options: [
      "1 \u2014 Very poor. Data is frequently incorrect, outdated, or inconsistent.",
      "2 \u2014 Poor. Data quality issues are common and regularly cause operational problems.",
      "3 \u2014 Moderate. Data is mostly accurate but has known quality gaps that we work around.",
      "4 \u2014 Good. Data is generally reliable and fit for purpose in most scenarios.",
      "5 \u2014 Excellent. Data is consistently accurate, complete, and trusted across the organisation.",
    ],
    required: true,
  },
  {
    id: "DQ2",
    section: "data_maturity",
    dimension: "DIM_DQ",
    text: "Which of the following data quality issues does your organisation experience? (Select all that apply)",
    type: "multi-select",
    options: [
      "Duplicate records (e.g., same customer entered multiple times)",
      "Missing or incomplete fields",
      "Inconsistent naming conventions or formats (e.g., date formats, currency symbols)",
      "Outdated records that are not regularly refreshed",
      "Data entered manually and subject to human error",
      "No standardised definitions for key metrics (e.g., \"revenue\" means different things to different teams)",
      "Data quality issues are rare or not a concern for us",
    ],
    required: true,
  },
  {
    id: "DQ3",
    section: "data_maturity",
    dimension: "DIM_DQ",
    text: "Does your organisation have any data validation or data cleansing processes in place?",
    type: "single-select",
    options: [
      "Yes \u2014 automated validation rules are built into our systems",
      "Yes \u2014 we carry out periodic manual data cleansing exercises",
      "Both automated validation and periodic manual cleansing",
      "Informal / ad-hoc cleansing only",
      "No formal validation or cleansing processes",
    ],
    required: true,
  },
  {
    id: "DQ4",
    section: "data_maturity",
    dimension: "DIM_DQ",
    text: "When different teams or departments report on the same metric (e.g., monthly revenue), how often do the figures match?",
    type: "single-select",
    options: [
      "Always \u2014 we have a single source of truth that all teams use",
      "Usually \u2014 minor discrepancies occur but are generally reconcilable",
      "Sometimes \u2014 differences are common and require investigation to resolve",
      "Rarely \u2014 different teams regularly report materially different numbers",
      "Never \u2014 data consistency is a persistent and unresolved problem",
    ],
    required: true,
  },

  // DIM_DI: Data Infrastructure & Tooling
  {
    id: "DI1",
    section: "data_maturity",
    dimension: "DIM_DI",
    text: "Which tools and technologies does your organisation currently use for data storage, analysis, and reporting? (Select all that apply)",
    type: "multi-select",
    options: [
      "Microsoft Excel / Google Sheets (primary data tool)",
      "Business Intelligence tools (Power BI, Tableau, Looker, Metabase)",
      "Cloud data warehouse (Snowflake, BigQuery, Redshift, Azure Synapse)",
      "On-premise database (MySQL, SQL Server, Oracle, PostgreSQL)",
      "ERP system with built-in reporting (SAP, Oracle ERP, Microsoft Dynamics, QuickBooks Enterprise)",
      "CRM with analytics (Salesforce, HubSpot)",
      "ETL / data integration tools (Fivetran, Talend, Azure Data Factory, dbt)",
      "Custom-built data pipelines or APIs",
      "No formal data tools \u2014 data is managed manually",
      "I don't know",
    ],
    required: true,
  },
  {
    id: "DI2",
    section: "data_maturity",
    dimension: "DIM_DI",
    text: "How does data move between systems in your organisation?",
    type: "single-select",
    options: [
      "Automatically via integrated APIs or data pipelines \u2014 data syncs in real time or on a schedule",
      "Semi-automatically \u2014 some integrations exist but many transfers require manual triggering",
      "Mostly manual \u2014 data is regularly exported (e.g., as Excel files) and re-imported into other systems",
      "Fully manual \u2014 employees move data between systems by hand",
      "I don't know",
    ],
    required: true,
  },
  {
    id: "DI3",
    section: "data_maturity",
    dimension: "DIM_DI",
    text: "Does your organisation have a data backup and disaster recovery plan?",
    type: "single-select",
    options: [
      "Yes \u2014 automated backups with a tested recovery plan",
      "Yes \u2014 backups exist but the recovery plan has not been formally tested",
      "Partial \u2014 some systems are backed up but not all",
      "No \u2014 backups are informal or non-existent",
      "I don't know",
    ],
    required: true,
  },
  {
    id: "DI4",
    section: "data_maturity",
    dimension: "DIM_DI",
    text: "How scalable is your current data infrastructure?",
    type: "likert",
    options: [
      "1 \u2014 Severely limited. Our infrastructure cannot handle current data volumes, let alone growth.",
      "2 \u2014 Limited. We are already experiencing performance or capacity constraints.",
      "3 \u2014 Adequate. Current infrastructure meets our needs but will require investment to scale.",
      "4 \u2014 Scalable. Infrastructure can accommodate significant growth with minor configuration changes.",
      "5 \u2014 Highly scalable. Cloud-native or elastic infrastructure that scales automatically with demand.",
    ],
    required: true,
  },

  // DIM_DG: Data Governance & Ownership
  {
    id: "DG1",
    section: "data_maturity",
    dimension: "DIM_DG",
    text: "Does your organisation have a formal data owner or data governance lead?",
    type: "single-select",
    options: [
      "Yes \u2014 a dedicated Chief Data Officer or equivalent senior role",
      "Yes \u2014 data ownership is assigned at the department or dataset level",
      "Informally \u2014 one person tends to manage data but without a formal mandate",
      "No \u2014 data governance is not formally assigned",
      "I don't know",
    ],
    required: true,
  },
  {
    id: "DG2",
    section: "data_maturity",
    dimension: "DIM_DG",
    text: "Which of the following data governance policies does your organisation have in place? (Select all that apply)",
    type: "multi-select",
    options: [
      "Data retention and deletion schedules",
      "Data classification (e.g., confidential, internal, public)",
      "Access controls (who can view, edit, or export specific datasets)",
      "Data privacy and protection (GDPR, UAE PDPL, or equivalent)",
      "Acceptable use of data for AI or machine learning applications",
      "None of the above",
    ],
    required: true,
  },
  {
    id: "DG3",
    section: "data_maturity",
    dimension: "DIM_DG",
    text: "How is access to sensitive data managed in your organisation?",
    type: "single-select",
    options: [
      "Role-based access controls are strictly enforced via system-level permissions",
      "Access is managed but controls are not always consistently applied",
      "Access is largely trust-based, with minimal technical controls",
      "There are no formal access controls \u2014 most employees can access most data",
      "I don't know",
    ],
    required: true,
  },
  {
    id: "DG4",
    section: "data_maturity",
    dimension: "DIM_DG",
    text: "Has your organisation experienced a data breach, data loss, or significant data security incident?",
    type: "single-select",
    options: [
      "Yes \u2014 and it was a significant incident with material business impact",
      "Yes \u2014 a minor incident occurred and was contained",
      "No \u2014 not to my knowledge",
      "I don't know",
    ],
    required: true,
  },

  // DIM_DC: Data Culture & Literacy
  {
    id: "DC1",
    section: "data_maturity",
    dimension: "DIM_DC",
    text: "How often do you personally use data to support or validate a business decision?",
    type: "likert",
    options: [
      "1 \u2014 Never. Decisions are made on experience and intuition alone.",
      "2 \u2014 Rarely. Data is occasionally referenced but is not central to decision-making.",
      "3 \u2014 Sometimes. Data informs some decisions but is not systematically used.",
      "4 \u2014 Often. Most significant decisions are supported by data and analysis.",
      "5 \u2014 Always. I default to data for all substantive decisions and track outcomes empirically.",
    ],
    required: true,
  },
  {
    id: "DC2",
    section: "data_maturity",
    dimension: "DIM_DC",
    text: "How data-literate would you describe the leadership team in your organisation?",
    type: "single-select",
    options: [
      "Highly literate \u2014 leaders actively seek out data, interpret dashboards, and challenge data quality.",
      "Moderately literate \u2014 most leaders are comfortable with standard reports and KPIs.",
      "Partially literate \u2014 some leaders engage with data; others prefer narrative or verbal briefings.",
      "Low literacy \u2014 data is rarely used in leadership discussions or strategic decisions.",
      "I don't know",
    ],
    required: true,
  },
  {
    id: "DC3",
    section: "data_maturity",
    dimension: "DIM_DC",
    text: "Does your organisation track key performance indicators (KPIs) consistently?",
    type: "single-select",
    options: [
      "Yes \u2014 KPIs are formally defined, tracked in a dashboard, and reviewed in regular governance meetings.",
      "Yes \u2014 KPIs exist and are tracked, but review is inconsistent or informal.",
      "Partially \u2014 some teams track KPIs; others do not.",
      "No \u2014 KPI tracking is not currently in place.",
    ],
    required: true,
  },
  {
    id: "DC4",
    section: "data_maturity",
    dimension: "DIM_DC",
    text: "When a business problem arises, what is the primary method used to diagnose its root cause?",
    type: "single-select",
    options: [
      "Quantitative data analysis (reviewing metrics, running queries, analysing trends)",
      "Structured qualitative review (interviews, surveys, focus groups)",
      "Management experience and intuition",
      "A mix of data and qualitative judgement",
      "The root cause is rarely formally investigated",
    ],
    required: true,
  },
  {
    id: "DC5",
    section: "data_maturity",
    dimension: "DIM_DC",
    text: "Has your organisation invested in data literacy or data skills training for employees?",
    type: "single-select",
    options: [
      "Yes \u2014 structured training delivered to all or most employees",
      "Yes \u2014 training offered but take-up was limited or voluntary",
      "No \u2014 but we are planning to do so",
      "No \u2014 and it is not currently a priority",
    ],
    required: true,
  },
];

// ─── PERSONAL AI ASSESSMENT ─────────────────────────────────────────────────

export const PERSONAL_AI_QUESTIONS: AssessmentQuestion[] = [
  // PAI_AD: AI Adoption Frequency & Depth
  {
    id: "PAI_AD1",
    section: "personal_ai",
    dimension: "PAI_AD",
    text: "How frequently do you use AI tools (e.g., ChatGPT, Claude, Copilot, Gemini) for professional tasks?",
    type: "single-select",
    options: [
      "Multiple times per day",
      "Once per day",
      "Several times per week",
      "Once per week or less",
      "Rarely (less than once per month)",
      "Never",
    ],
    required: true,
  },
  {
    id: "PAI_AD2",
    section: "personal_ai",
    dimension: "PAI_AD",
    text: "For which of the following professional tasks do you currently use AI? (Select all that apply)",
    type: "multi-select",
    options: [
      "Drafting emails, reports, or documents",
      "Summarising long documents or meeting notes",
      "Research and information retrieval",
      "Data analysis or interpretation",
      "Generating ideas or brainstorming",
      "Writing code or automating workflows",
      "Translation or language editing",
      "Preparing presentations or visual content",
      "Customer communication or response drafting",
      "Strategic scenario planning or analysis",
      "I do not currently use AI for professional tasks",
    ],
    required: true,
  },
  {
    id: "PAI_AD3",
    section: "personal_ai",
    dimension: "PAI_AD",
    text: "How would you describe your current depth of AI usage?",
    type: "single-select",
    options: [
      "Surface level",
      "Functional",
      "Proficient",
      "Advanced",
      "Expert",
    ],
    required: true,
    helpText: "Surface = basic queries; Expert = complex multi-step workflows and custom integrations.",
  },
  {
    id: "PAI_AD4",
    section: "personal_ai",
    dimension: "PAI_AD",
    text: "Over the past six months, how has your AI usage changed?",
    type: "single-select",
    options: [
      "Significantly increased \u2014 AI is now a core part of how I work",
      "Moderately increased \u2014 I use AI more than before",
      "Remained the same",
      "Decreased \u2014 I have found AI less useful than expected",
      "I have not used AI consistently enough to observe a trend",
    ],
    required: true,
  },

  // PAI_TB: AI Tool Breadth
  {
    id: "PAI_TB1",
    section: "personal_ai",
    dimension: "PAI_TB",
    text: "Which categories of AI tools have you personally used? (Select all that apply)",
    type: "multi-select",
    options: [
      "General-purpose conversational AI (ChatGPT, Claude, Gemini, Copilot)",
      "AI writing assistants (Jasper, Copy.ai, Grammarly AI)",
      "AI image or video generation (Midjourney, DALL-E, Runway, Sora)",
      "AI presentation tools (Gamma, Beautiful.ai, Tome)",
      "AI coding assistants (GitHub Copilot, Cursor, Replit AI)",
      "AI data analysis (Julius, ChatGPT Advanced Data Analysis, Noteable)",
      "AI meeting tools (Otter.ai, Fireflies, Microsoft Copilot for Teams)",
      "AI search (Perplexity, You.com, Bing AI)",
      "AI for workflow automation (Zapier AI, Make with AI, n8n)",
      "AI agents or multi-step reasoning tools (Claude Projects, GPT-4o with tools, Devin)",
      "None of the above",
    ],
    required: true,
  },
  {
    id: "PAI_TB2",
    section: "personal_ai",
    dimension: "PAI_TB",
    text: "When starting a new task, how often do you consider whether AI could help?",
    type: "likert",
    options: [
      "1 \u2014 Never. I default to manual work without considering AI.",
      "2 \u2014 Rarely. I occasionally think of AI after beginning a task.",
      "3 \u2014 Sometimes. AI is one of several options I consider.",
      "4 \u2014 Often. AI is usually my first consideration for tasks where it could be relevant.",
      "5 \u2014 Always. I systematically evaluate AI applicability before starting any significant task.",
    ],
    required: true,
  },
  {
    id: "PAI_TB3",
    section: "personal_ai",
    dimension: "PAI_TB",
    text: "Have you created or integrated an AI-powered workflow (e.g., connecting AI to a spreadsheet, automating a process)?",
    type: "single-select",
    options: [
      "Yes \u2014 I have designed and implemented multiple AI workflows",
      "Yes \u2014 I have built at least one AI-assisted workflow",
      "I have attempted to but faced technical barriers",
      "No \u2014 but I am interested in doing so",
      "No \u2014 I don't see the need",
    ],
    required: true,
  },

  // PAI_PE: Prompt Engineering Proficiency
  {
    id: "PAI_PE1",
    section: "personal_ai",
    dimension: "PAI_PE",
    text: "How would you describe your typical approach to writing prompts for AI?",
    type: "single-select",
    options: ["Conversational", "Directive", "Structured", "Engineered", "Systematic"],
    required: true,
    helpText: "Conversational = natural language chat; Systematic = structured frameworks with roles, constraints, and output specs.",
  },
  {
    id: "PAI_PE2",
    section: "personal_ai",
    dimension: "PAI_PE",
    text: "Which of the following prompt engineering techniques have you used? (Select all that apply)",
    type: "multi-select",
    options: [
      "Role prompting (e.g., \"You are an expert financial analyst...\")",
      "Few-shot prompting (providing 2\u20133 examples of the desired output)",
      "Chain-of-thought prompting (asking AI to show its reasoning step by step)",
      "System prompts or custom instructions",
      "Prompt chaining (connecting the output of one prompt to the input of the next)",
      "Output format specification (e.g., JSON, Markdown table, numbered list)",
      "Constraint specification (e.g., \"do not include X\", \"limit response to 200 words\")",
      "Temperature or parameter adjustment (in API or advanced settings)",
      "None of the above \u2014 I am not familiar with these techniques",
    ],
    required: true,
  },
  {
    id: "PAI_PE3",
    section: "personal_ai",
    dimension: "PAI_PE",
    text: "Write a prompt you would use to get AI to help with a task relevant to your role. Write it exactly as you would type it into an AI tool.",
    type: "long-text",
    required: true,
    minLength: 20,
    maxLength: 400,
    helpText: "This is a practical demonstration \u2014 write it as if you were actually using the tool right now.",
  },
  {
    id: "PAI_PE4",
    section: "personal_ai",
    dimension: "PAI_PE",
    text: "When an AI tool gives you an output that is not quite right, what do you typically do?",
    type: "single-select",
    options: [
      "Accept the output as-is, even if imperfect",
      "Rephrase my original request and try again",
      "Add specific feedback or corrections to my follow-up prompt (\"This is too long, please focus on...\")",
      "Systematically diagnose why the first prompt failed and redesign it",
      "Use multiple follow-up prompts to iteratively refine the output toward a clear target",
    ],
    required: true,
  },

  // PAI_CE: AI Critical Evaluation
  {
    id: "PAI_CE1",
    section: "personal_ai",
    dimension: "PAI_CE",
    text: "How confident are you in your ability to identify when an AI tool has generated incorrect or misleading information?",
    type: "likert",
    options: [
      "1 \u2014 Not confident at all. I generally trust AI outputs.",
      "2 \u2014 Slightly confident. I occasionally notice obvious errors but may miss subtle ones.",
      "3 \u2014 Moderately confident. I apply judgement and cross-reference important outputs.",
      "4 \u2014 Quite confident. I regularly fact-check AI outputs and have a calibrated sense of where AI tends to fail.",
      "5 \u2014 Highly confident. I have a sophisticated understanding of AI failure modes and apply systematic verification.",
    ],
    required: true,
  },
  {
    id: "PAI_CE2",
    section: "personal_ai",
    dimension: "PAI_CE",
    text: "What is your standard practice after receiving an AI-generated output that you plan to use in your work?",
    type: "single-select",
    options: [
      "I use AI output directly without modification \u2014 I trust it",
      "I review the output for obvious errors or tone issues before using",
      "I fact-check key claims against authoritative sources",
      "I treat AI output as a first draft that I substantially edit before use",
      "I use AI output as a thinking prompt and write the final product myself",
    ],
    required: true,
  },
  {
    id: "PAI_CE3",
    section: "personal_ai",
    dimension: "PAI_CE",
    text: "Which of the following statements about AI do you believe to be true? (Select all you agree with)",
    type: "multi-select",
    options: [
      "AI can produce plausible-sounding but entirely fabricated information",
      "AI tools can embed or amplify biases present in their training data",
      "The same prompt can produce different outputs at different times",
      "AI does not \"understand\" content \u2014 it predicts statistically likely outputs",
      "AI tools can access real-time information from the internet (always)",
      "AI-generated content is always factually accurate if it sounds confident",
      "AI tools can fully replace human judgement in complex, ambiguous situations",
    ],
    required: true,
    helpText: "Select all statements you believe are true. Some are correct and some are not.",
  },
  {
    id: "PAI_CE4",
    section: "personal_ai",
    dimension: "PAI_CE",
    text: "Have you established personal protocols or boundaries for how you use AI in your professional work?",
    type: "single-select",
    options: [
      "Yes \u2014 I have clear personal guidelines about appropriate and inappropriate AI use in my role",
      "Informally \u2014 I have a general sense of where I will and won't use AI",
      "Not yet \u2014 but I am thinking about it",
      "No \u2014 I use AI wherever it is helpful without formal criteria",
    ],
    required: true,
  },

  // PAI_TW: AI Tool & Workflow Sophistication
  {
    id: "PAI_TW1",
    section: "personal_ai",
    dimension: "PAI_TW",
    text: "Which of the following advanced AI features have you personally used?",
    type: "multi-select",
    options: [
      "Claude Projects (persistent workspace with custom instructions)",
      "Claude Skills (reusable prompt templates that trigger automatically)",
      "Claude Cowork (collaborative AI workspace for complex tasks)",
      "Claude Code (AI-powered coding assistant in terminal/IDE)",
      "Claude Artifacts (interactive documents, code, and visualizations)",
      "MCP Connectors (connecting Claude to external tools and data sources)",
      "Custom GPTs or similar custom AI assistants",
      "AI workflow automation (Zapier, Make, n8n with AI steps)",
      "API-based AI integrations (calling AI models programmatically)",
      "None of the above",
    ],
    required: true,
  },
  {
    id: "PAI_TW2",
    section: "personal_ai",
    dimension: "PAI_TW",
    text: "How many Claude Projects (or equivalent AI workspaces with persistent instructions) have you set up for your work?",
    type: "single-select",
    options: [
      "None \u2014 I don't use Projects",
      "1 project",
      "2-3 projects for different work areas",
      "4-5 projects covering most of my workflow",
      "6+ projects \u2014 I have a project for every major work stream",
    ],
    required: true,
  },
  {
    id: "PAI_TW3",
    section: "personal_ai",
    dimension: "PAI_TW",
    text: "Have you created or used any Claude Skills (reusable prompt templates) in your work?",
    type: "single-select",
    options: [
      "I don't know what Claude Skills are",
      "I've heard of them but haven't used any",
      "I've enabled and used pre-built skills from Anthropic",
      "I've created 1-2 custom skills for my own use",
      "I've created multiple skills and shared them with my team",
    ],
    required: true,
  },
  {
    id: "PAI_TW4",
    section: "personal_ai",
    dimension: "PAI_TW",
    text: "How would you describe your approach to automating repetitive AI tasks?",
    type: "single-select",
    options: [
      "I type everything from scratch each time",
      "I copy-paste previous prompts and modify them",
      "I have saved templates I reuse regularly",
      "I use Claude Skills or similar tools to automate my most common tasks",
      "I've built end-to-end automated workflows where AI runs with minimal manual input",
    ],
    required: true,
  },
  {
    id: "PAI_TW5",
    section: "personal_ai",
    dimension: "PAI_TW",
    text: "Which of the following have you done to customize Claude for your specific role?",
    type: "multi-select",
    options: [
      "Written custom instructions for a Claude Project",
      "Created a Claude Skill tailored to my workflow",
      "Connected Claude to external tools via MCP",
      "Set up Claude Code for development tasks",
      "Used Claude Cowork for complex multi-step projects",
      "Uploaded reference documents to a Claude Project for persistent context",
      "Shared custom skills or projects with colleagues",
      "None of the above",
    ],
    required: true,
  },
];

// ─── COMPANY AI ASSESSMENT ──────────────────────────────────────────────────

export const COMPANY_AI_QUESTIONS: AssessmentQuestion[] = [
  // Respondent Context (RC) — used for weighting
  {
    id: "RC1",
    section: "company_ai",
    dimension: "RC",
    text: "How long have you been with this organisation?",
    type: "single-select",
    options: [
      "Less than 6 months",
      "6 months \u2013 2 years",
      "2\u20135 years",
      "5\u201310 years",
      "More than 10 years",
    ],
    required: true,
  },
  {
    id: "RC2",
    section: "company_ai",
    dimension: "RC",
    text: "How much visibility do you have into your organisation's overall strategic direction and technology decisions?",
    type: "single-select",
    options: [
      "Full visibility \u2014 I am directly involved in or informed of all major strategic and technology decisions",
      "Significant visibility \u2014 I am informed of most strategic decisions, particularly those affecting my function",
      "Moderate visibility \u2014 I am aware of high-level direction but not detailed strategic planning",
      "Limited visibility \u2014 I am primarily focused on my own area and have limited insight into organisation-wide strategy",
      "No visibility \u2014 I have no meaningful insight into the organisation's strategic direction",
    ],
    required: true,
  },

  // CAI_SV: AI Strategy & Vision
  {
    id: "CAI_SV1",
    section: "company_ai",
    dimension: "CAI_SV",
    text: "Does your organisation have a formal AI strategy?",
    type: "single-select",
    options: [
      "Yes \u2014 AI is a named strategic priority with defined goals, a roadmap, and executive ownership",
      "Partially \u2014 AI has been discussed at leadership level but is not yet formally codified in strategy",
      "No \u2014 AI has not yet entered the organisation's formal strategic planning",
      "I don't know",
    ],
    required: true,
  },
  {
    id: "CAI_SV2",
    section: "company_ai",
    dimension: "CAI_SV",
    text: "Who is the executive sponsor or primary champion for AI in your organisation?",
    type: "single-select",
    options: [
      "The CEO / Managing Director personally champions AI adoption",
      "The CTO or Chief Digital Officer leads AI strategy",
      "A dedicated AI / Innovation team with C-suite backing",
      "AI is sponsored at the divisional or department level, not at the executive level",
      "There is no clear executive sponsor for AI",
      "I don't know",
    ],
    required: true,
  },
  {
    id: "CAI_SV3",
    section: "company_ai",
    dimension: "CAI_SV",
    text: "Does your organisation allocate a specific budget for AI initiatives?",
    type: "single-select",
    options: [
      "Yes \u2014 AI has a formal, dedicated budget line",
      "Yes \u2014 AI spending is approved project-by-project but there is no standing budget",
      "No \u2014 AI spending comes from general IT or operational budgets without formal allocation",
      "No \u2014 there is no active AI investment at this time",
      "I don't know",
    ],
    required: true,
  },
  {
    id: "CAI_SV4",
    section: "company_ai",
    dimension: "CAI_SV",
    text: "To what extent is AI integrated into your organisation's long-term business plan (3\u20135 years)?",
    type: "likert",
    options: [
      "1 \u2014 Not at all. AI is not referenced in our long-term planning.",
      "2 \u2014 Peripherally. AI is acknowledged as a future consideration but not planned for.",
      "3 \u2014 Moderately. AI features in some parts of the plan as a supporting capability.",
      "4 \u2014 Significantly. AI is a key enabler of multiple strategic objectives.",
      "5 \u2014 Centrally. AI is a foundational element of our long-term competitive strategy.",
    ],
    required: true,
  },
  {
    id: "CAI_SV5",
    section: "company_ai",
    dimension: "CAI_SV",
    text: "In one or two sentences, describe your organisation's ambition or vision for AI over the next 2\u20133 years.",
    type: "long-text",
    required: true,
    minLength: 50,
    maxLength: 300,
  },

  // CAI_IT: AI Infrastructure & Tooling
  {
    id: "CAI_IT1",
    section: "company_ai",
    dimension: "CAI_IT",
    text: "What is your organisation's primary software and cloud environment?",
    type: "single-select",
    options: [
      "Microsoft ecosystem (Azure, M365, Teams, Dynamics)",
      "Google ecosystem (Google Workspace, Google Cloud)",
      "SAP or Oracle ecosystem (enterprise ERP)",
      "Salesforce ecosystem (CRM-centric)",
      "A hybrid of cloud and on-premise systems from multiple vendors",
      "Predominantly legacy / on-premise systems with limited cloud adoption",
      "I don't know",
    ],
    required: true,
  },
  {
    id: "CAI_IT2",
    section: "company_ai",
    dimension: "CAI_IT",
    text: "Are any AI capabilities currently live and integrated into your business systems?",
    type: "single-select",
    options: [
      "Yes \u2014 multiple AI capabilities are live and actively used (e.g., Copilot, Einstein, etc.)",
      "Yes \u2014 at least one AI capability is live and integrated into a business process",
      "Partially \u2014 AI features exist in our tools but are not actively used",
      "No \u2014 no AI capabilities are currently live",
      "I don't know",
    ],
    required: true,
  },
  {
    id: "CAI_IT3",
    section: "company_ai",
    dimension: "CAI_IT",
    text: "Which of the following AI infrastructure elements does your organisation have in place? (Select all that apply)",
    type: "multi-select",
    options: [
      "A centralised AI platform or AI development environment",
      "API integrations between AI tools and core business systems",
      "An AI-ready data warehouse or data lake",
      "Custom machine learning models trained on internal data",
      "AI-powered dashboards or analytics interfaces",
      "Robotic Process Automation (RPA) deployments",
      "A conversational AI interface (chatbot, virtual assistant) for internal or external use",
      "Vector databases or knowledge bases for AI retrieval",
      "None of the above",
      "I don't know",
    ],
    required: true,
  },

  // CAI_PI: AI Process Integration
  {
    id: "CAI_PI1",
    section: "company_ai",
    dimension: "CAI_PI",
    text: "In which business functions has your organisation deployed or piloted AI? (Select all that apply)",
    type: "multi-select",
    options: [
      "Finance & Accounting (e.g., automated reconciliation, invoice processing, financial forecasting)",
      "Sales & Marketing (e.g., lead scoring, content generation, customer segmentation)",
      "Operations & Supply Chain (e.g., demand forecasting, inventory optimisation, routing)",
      "Human Resources (e.g., CV screening, employee engagement analytics, onboarding automation)",
      "Customer Service (e.g., chatbots, automated ticket routing, sentiment analysis)",
      "Legal & Compliance (e.g., contract review, regulatory monitoring)",
      "IT & Security (e.g., anomaly detection, automated patching, threat intelligence)",
      "Product & R&D (e.g., AI-assisted design, synthetic data generation)",
      "None of the above",
      "I don't know",
    ],
    required: true,
  },
  {
    id: "CAI_PI2",
    section: "company_ai",
    dimension: "CAI_PI",
    text: "Describe the most impactful AI deployment or pilot your organisation has undertaken. If none, describe the most promising opportunity.",
    type: "long-text",
    required: true,
    minLength: 50,
    maxLength: 350,
  },
  {
    id: "CAI_PI3",
    section: "company_ai",
    dimension: "CAI_PI",
    text: "How does your organisation prioritise where to apply AI?",
    type: "single-select",
    options: [
      "A structured, data-driven prioritisation framework based on ROI, feasibility, and strategic alignment",
      "Informed by leadership intuition and strategic priorities",
      "Driven by vendor recommendations or industry peer benchmarking",
      "Organic / bottom-up \u2014 AI adoption happens where individual employees take initiative",
      "We have not yet begun formally prioritising AI integration",
      "I don't know",
    ],
    required: true,
  },
  {
    id: "CAI_PI4",
    section: "company_ai",
    dimension: "CAI_PI",
    text: "What are the top barriers to deeper AI integration in your organisation? (Select up to 2)",
    type: "multi-select",
    maxSelections: 2,
    options: [
      "Lack of clean, structured data",
      "Insufficient technical expertise or AI talent",
      "Budget constraints",
      "Cultural resistance to change",
      "Concerns about data security or privacy",
      "Unclear ROI or business case",
      "Lack of leadership alignment or executive sponsorship",
      "Regulatory or compliance constraints",
      "Adequate vendor or partner ecosystem",
      "We do not face significant barriers \u2014 AI integration is progressing well",
    ],
    required: true,
  },

  // CAI_TC: AI Talent & Capability
  {
    id: "CAI_TC1",
    section: "company_ai",
    dimension: "CAI_TC",
    text: "How would you assess the current level of AI expertise within your organisation?",
    type: "likert",
    options: [
      "1 \u2014 None. We have no individuals with meaningful AI skills.",
      "2 \u2014 Minimal. One or two individuals have basic AI awareness but no technical capability.",
      "3 \u2014 Emerging. We have a small number of technically capable individuals experimenting with AI.",
      "4 \u2014 Developing. We have a dedicated team with AI skills and are actively building capability.",
      "5 \u2014 Strong. We have a mature, well-resourced AI capability with data scientists, ML engineers, and AI product managers.",
    ],
    required: true,
  },
  {
    id: "CAI_TC2",
    section: "company_ai",
    dimension: "CAI_TC",
    text: "Has your organisation invested in AI training or upskilling for employees?",
    type: "single-select",
    options: [
      "Yes \u2014 a structured, organisation-wide AI upskilling programme is underway",
      "Yes \u2014 targeted training for specific roles or teams",
      "Informally \u2014 individuals have undertaken self-directed AI learning (online courses, etc.)",
      "No \u2014 but it is planned for the next 12 months",
      "No \u2014 AI training is not currently a priority",
    ],
    required: true,
  },
  {
    id: "CAI_TC3",
    section: "company_ai",
    dimension: "CAI_TC",
    text: "To what extent does your organisation rely on external vendors or consultants for AI work?",
    type: "single-select",
    options: [
      "Fully internally delivered \u2014 we have the capability to design, build, and manage AI systems in-house",
      "Primarily internal with occasional external support",
      "Balanced \u2014 internal team works in partnership with external specialists",
      "Primarily external \u2014 we rely heavily on vendors or consultants for AI work",
      "Entirely external \u2014 all AI initiatives are outsourced",
    ],
    required: true,
  },

  // CAI_GE: AI Governance & Ethics
  {
    id: "CAI_GE1",
    section: "company_ai",
    dimension: "CAI_GE",
    text: "Does your organisation have a formal AI governance or acceptable use policy?",
    type: "single-select",
    options: [
      "Yes \u2014 a comprehensive AI policy covering acceptable use, data handling, and accountability is in place and communicated",
      "Yes \u2014 a basic policy exists but is not comprehensively applied",
      "In development \u2014 a policy is being drafted",
      "No \u2014 and it is not currently planned",
      "I don't know",
    ],
    required: true,
  },
  {
    id: "CAI_GE2",
    section: "company_ai",
    dimension: "CAI_GE",
    text: "Does your organisation monitor or audit the quality and accuracy of AI-generated outputs?",
    type: "single-select",
    options: [
      "Yes \u2014 automated monitoring and human oversight processes are in place",
      "Yes \u2014 periodic manual reviews of AI outputs are conducted",
      "Informal \u2014 occasional spot-checks but no systematic review",
      "No \u2014 AI outputs are not currently monitored or audited",
      "Not applicable \u2014 we have no AI in production",
    ],
    required: true,
  },
  {
    id: "CAI_GE3",
    section: "company_ai",
    dimension: "CAI_GE",
    text: "Which of the following AI-related risks has your organisation formally considered? (Select all that apply)",
    type: "multi-select",
    options: [
      "Model bias or unfair outcomes",
      "Data privacy violations resulting from AI use",
      "Over-reliance on AI outputs without human verification",
      "Employees sharing sensitive or proprietary data with public AI tools",
      "Reputational risk from incorrect or inappropriate AI-generated content",
      "Intellectual property risks (using AI to generate content based on protected material)",
      "None of the above have been formally considered",
    ],
    required: true,
  },
  {
    id: "CAI_GE4",
    section: "company_ai",
    dimension: "CAI_GE",
    text: "What do you consider the single most significant AI-related risk for your organisation right now?",
    type: "long-text",
    required: true,
    minLength: 30,
    maxLength: 200,
  },
];

// ─── Helper: get questions by section slug ──────────────────────────────────

const SECTION_MAP: Record<string, AssessmentQuestion[]> = {
  registration: REGISTRATION_QUESTIONS,
  "data-maturity": DATA_MATURITY_QUESTIONS,
  data_maturity: DATA_MATURITY_QUESTIONS,
  "personal-ai": PERSONAL_AI_QUESTIONS,
  personal_ai: PERSONAL_AI_QUESTIONS,
  "company-ai": COMPANY_AI_QUESTIONS,
  company_ai: COMPANY_AI_QUESTIONS,
};

export function getQuestionsForSection(section: string): AssessmentQuestion[] {
  return SECTION_MAP[section] || [];
}

export function sectionSlugToDbKey(slug: string): string {
  const map: Record<string, string> = {
    registration: "registration",
    "data-maturity": "data_maturity",
    "personal-ai": "personal_ai",
    "company-ai": "company_ai",
  };
  return map[slug] || slug;
}

export function dbKeyToSectionSlug(key: string): string {
  const map: Record<string, string> = {
    registration: "registration",
    data_maturity: "data-maturity",
    personal_ai: "personal-ai",
    company_ai: "company-ai",
  };
  return map[key] || key;
}
